[package]
name = 'Econia'
version = '2.0.6' # Per SemVer

[addresses]
econia = '0xba9dc1be4f5afacf8e695c0611d8d761d9188bffd2d5b1d77470eaeaa2250512'
# Mock users for unit tests
user = '0x1234'
user_0 = '0x2345'
user_1 = '0x3456'
user_2 = '0x4567'
user_3 = '0x5678'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core'
subdir = 'aptos-move/framework/aptos-framework'
rev = 'e1c6a5713301ed72bf3a846ab9536d002ac801d6'