[package]
name = 'Econia'
version = '3.0.0' # Per SemVer
upgrade_policy = 'compatible'

[addresses]
econia = '0xda062132ebeb6e93345e2455596ac4e1e7a0df0a40f9cbc15f4846c7e178dc6f'
# Mock users for unit tests
user = '0x1234'
user_0 = '0x2345'
user_1 = '0x3456'
user_2 = '0x4567'
user_3 = '0x5678'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core'
subdir = 'aptos-move/framework/aptos-framework'
rev = '4efdb8191c12e63e2fda74e732ef462f1710d671'
